const HTTP_STATUS= Object.freeze({
    OK:200,
    CREATED:201,
    BAD_REQUEST:400,
    NOT_FOUND:404,
    INTERNAL_ERROR:500,
    AUTHORIZATION_REQUIRED:401,
    FORBIDDEN:403
});


module.exports={HTTP_STATUS}